CREATE TABLE hive.tead.housing (
    "month_date_yyyymm" varchar,
    "county_fips" varchar,
    "county name" varchar,
    "median_listing_price" varchar,
    "median_listing_price_mm" varchar,
    "median_listing_price_yy" varchar,
    "active_listing_count" varchar,
    "active_listing_count_mm" varchar,
    "active_listing_count_yy" varchar,
    "median_days_on_market" varchar,
    "median_days_on_market_mm" varchar,
    "median_days_on_market_yy" varchar,
    "new_listing_count" varchar,
    "new_listing_count_mm" varchar,
    "new_listing_count_yy" varchar,
    "price_increased_count" varchar,
    "price_increased_count_mm" varchar,
    "yy_tnuoc_desaercni_ecirp" varchar,
    "dcile_ihvreafed_shhrg" varchar,
    "price_increased_share_mm" varchar,
    "price_increased_share_yy" varchar,
    "price_reduced_count" varchar,
    "price_reduced_count_mm" varchar,
    "price_reduced_count_yy" varchar,
    "price_reduced_share" varchar,
    "price_reduced_share_mm" varchar,
    "price_reduced_share_yy" varchar,
    "pending_listing_count" varchar,
    "pending_listing_count_mm" varchar,
    "pending_listing_count_yy" varchar,
    "median_listing_price_per_square_foot" varchar,
    "median_listing_price_per_square_foot_mm" varchar,
    "median_listing_price_per_square_foot_yy" varchar,
    "median_square_feet" varchar,
    "median_square_feet_mm" varchar,
    "median_square_feet_yy" varchar,
    "AVERAGE_LISTING_PRICE" varchar,
    "average_listing_price_mm" varchar,
    "average_listing_price_yy" varchar,
    "total_listing_count" varchar,
    "total_listing_count_mm" varchar,
    "total_listing_count_yy" varchar,
    "PENDING_RATIO" varchar,
    "pending_ratio_mm" varchar,
    "pending_ratio_yy" varchar,
    "quality_flag" varchar,
    "banana_index" varchar,
    "__temp__" varchar,
    "col with spaces & symbols!" varchar
)
WITH (
    format = 'CSV',
    external_location = 's3a://warehouse/raw/housing/',
    skip_header_line_count = 1,
    csv_separator = ',',
    csv_quote = '"',
    csv_escape = '"'
);