CREATE TABLE iceberg.tead.housing_bronze
WITH (
    format = 'PARQUET',
    location = 's3a://warehouse/bronze/housing/'
)
AS
SELECT
    "month_date_yyyymm",
    "county_fips",
    "county name",
    try_cast("median_listing_price" as double) AS "median_listing_price",
    try_cast("median_listing_price_mm" as double) AS "median_listing_price_mm",
    try_cast("median_listing_price_yy" as double) AS "median_listing_price_yy",
    try_cast("active_listing_count" as double) AS "active_listing_count",
    try_cast("active_listing_count_mm" as double) AS "active_listing_count_mm",
    try_cast("active_listing_count_yy" as double) AS "active_listing_count_yy",
    try_cast("median_days_on_market" as double) AS "median_days_on_market",
    try_cast("median_days_on_market_mm" as double) AS "median_days_on_market_mm",
    try_cast("median_days_on_market_yy" as double) AS "median_days_on_market_yy",
    try_cast("new_listing_count" as double) AS "new_listing_count",
    try_cast("new_listing_count_mm" as double) AS "new_listing_count_mm",
    try_cast("new_listing_count_yy" as double) AS "new_listing_count_yy",
    try_cast("price_increased_count" as double) AS "price_increased_count",
    try_cast("price_increased_count_mm" as double) AS "price_increased_count_mm",
    try_cast("yy_tnuoc_desaercni_ecirp" as double) AS "yy_tnuoc_desaercni_ecirp",
    "dcile_ihvreafed_shhrg", -- Parece ser texto misturado na tua amostra, mantenho como texto
    try_cast("price_increased_share_mm" as double) AS "price_increased_share_mm",
    try_cast("price_increased_share_yy" as double) AS "price_increased_share_yy",
    try_cast("price_reduced_count" as double) AS "price_reduced_count",
    try_cast("price_reduced_count_mm" as double) AS "price_reduced_count_mm",
    try_cast("price_reduced_count_yy" as double) AS "price_reduced_count_yy",
    try_cast("price_reduced_share" as double) AS "price_reduced_share",
    try_cast("price_reduced_share_mm" as double) AS "price_reduced_share_mm",
    try_cast("price_reduced_share_yy" as double) AS "price_reduced_share_yy",
    try_cast("pending_listing_count" as double) AS "pending_listing_count",
    try_cast("pending_listing_count_mm" as double) AS "pending_listing_count_mm",
    try_cast("pending_listing_count_yy" as double) AS "pending_listing_count_yy",
    try_cast("median_listing_price_per_square_foot" as double) AS "median_listing_price_per_square_foot",
    try_cast("median_listing_price_per_square_foot_mm" as double) AS "median_listing_price_per_square_foot_mm",
    try_cast("median_listing_price_per_square_foot_yy" as double) AS "median_listing_price_per_square_foot_yy",
    try_cast("median_square_feet" as double) AS "median_square_feet",
    try_cast("median_square_feet_mm" as double) AS "median_square_feet_mm",
    try_cast("median_square_feet_yy" as double) AS "median_square_feet_yy",
    try_cast("AVERAGE_LISTING_PRICE" as double) AS "AVERAGE_LISTING_PRICE",
    try_cast("average_listing_price_mm" as double) AS "average_listing_price_mm",
    try_cast("average_listing_price_yy" as double) AS "average_listing_price_yy",
    try_cast("total_listing_count" as double) AS "total_listing_count",
    try_cast("total_listing_count_mm" as double) AS "total_listing_count_mm",
    try_cast("total_listing_count_yy" as double) AS "total_listing_count_yy",
    try_cast("PENDING_RATIO" as double) AS "PENDING_RATIO",
    try_cast("pending_ratio_mm" as double) AS "pending_ratio_mm",
    try_cast("pending_ratio_yy" as double) AS "pending_ratio_yy",
    try_cast("quality_flag" as double) AS "quality_flag",
    try_cast("banana_index" as double) AS "banana_index",
    "__temp__",
    "col with spaces & symbols!"
FROM hive.tead.housing